proj7: vkiril2Proj7.cpp Island.cpp Island.hpp MyList.cpp MyList.hpp Archipelago.cpp Archipelago.hpp MyStack.hpp
	g++ -std=c++11 -o proj7 vkiril2Proj7.cpp Island.cpp MyList.cpp Archipelago.cpp

clean:
	rm proj7
